# Generated by Django 3.1.1 on 2021-12-06 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library', '0002_auto_20211206_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.IntegerField(choices=[(0, 'STUDENT'), (1, 'EMPLOYED'), (2, 'RETIRED')], default=0)),
                ('age', models.IntegerField(choices=[(0, 'UNDER 18'), (1, '18-35'), (2, 'ABOVE 35')], default=1)),
                ('location', models.CharField(max_length=15)),
                ('caretaker', models.IntegerField(choices=[(0, 'GOOD'), (1, 'AVERAGE'), (2, 'POOR')], default=1)),
                ('read_books', models.ManyToManyField(blank=True, to='library.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
