# Generated by Django 3.1.1 on 2021-12-09 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_bookcomment_reviewcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
