# Generated by Django 3.1.1 on 2021-12-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20211206_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date']},
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
